//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Licitaciones.BaseDato
{
    using System;
    using System.Collections.Generic;
    
    public partial class GrlType
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public short TypeConfig_Id { get; set; }
        public short Order { get; set; }
        public string Description { get; set; }
        public byte[] Icon { get; set; }
        public Nullable<sbyte> Deleted { get; set; }
    }
}
