//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Licitaciones.BaseDato
{
    using System;
    using System.Collections.Generic;
    
    public partial class PryEmpresa
    {
        public int Id { get; set; }
        public string Namber { get; set; }
        public string Name { get; set; }
        public string RazonSocial { get; set; }
        public string CUIT { get; set; }
        public string IngBrutos { get; set; }
        public string PhoneR { get; set; }
        public string FaxR { get; set; }
        public string AddressR { get; set; }
        public string Email { get; set; }
        public string AddressS { get; set; }
        public Nullable<int> IsArchived { get; set; }
        public string Observation { get; set; }
        public string IericNro { get; set; }
        public string InsConsejoNro { get; set; }
        public Nullable<System.DateTime> InscConsejoFecha { get; set; }
        public Nullable<int> IsUte { get; set; }
        public string Caracter { get; set; }
        public string TelefonoEspecial { get; set; }
        public string EmailEspecial { get; set; }
        public string NombrePersonaContacto { get; set; }
        public string TelefonoPersonaContacto { get; set; }
        public string EmailPersonaContacto { get; set; }
        public string NombreRepresentanteLegal { get; set; }
        public string NombreRepresentanteTecnico { get; set; }
    }
}
